server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xcs?useSSL=false
    username: root
    password: xdq123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  jackson:
    serialization:
      indent_output: true
  thymeleaf:
    cache: false
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    host: 192.168.3.128
    password: xdq123
data:
  memory:
    strategy: memory

file:
  upload:
    path: C:/xcs/upload_file/